title: Fulton's blog and homepage
description: The blog and project page of Fulton Browne
social_link: dev
social_username: fultonbrowne
github_repo: ara-android
github_username: fultonbrowne
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /web/
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
